# Generated by Django 4.1.3 on 2023-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="name",),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user", name="last_name", field=models.CharField(max_length=255),
        ),
    ]
