# Generated by Django 4.1.3 on 2023-05-13 05:56

from django.db import migrations, models
import django.db.models.deletion
import file_management.models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0001_initial"),
        ("file_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="file", old_name="name", new_name="title",),
        migrations.RenameField(
            model_name="file", old_name="created_at", new_name="uploaded_at",
        ),
        migrations.RemoveField(model_name="file", name="description",),
        migrations.RemoveField(model_name="file", name="published",),
        migrations.RemoveField(model_name="file", name="updated_at",),
        migrations.AddField(
            model_name="file",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="module.module",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=file_management.models.get_upload_path),
        ),
    ]
