# Generated by Django 4.1.3 on 2023-05-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0003_file_description_file_uploaded_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file", old_name="uploaded_at", new_name="created_at",
        ),
        migrations.RenameField(model_name="file", old_name="title", new_name="name",),
    ]
